default:	Pi_Trapezoidal
all:	Pi_Trapezoidal

Pi_Trapezoidal: Pi_Trapezoidal.cpp
	mpic++ Pi_Trapezoidal.cpp  -o Pi_Trapezoidal

clean:
	rm -f Pi_Trapezoidal Pi_Trapezoidal.o

distclean:
	rm -f Makefile
